const SubOfTheMonth = [
    {
        subName: "Supreme Meat",
        breadOption: "Sub Rolls",
        subSize: "Large",
        drinkChoice: "None",
        subTopArray: ["Bacon", "Pulled Pork", "Sandwich Ham", "Smoked Turkey Ham", "Lettuce", "Tomatoes", "Cheese", "Gherkins"],
        orderTotal: 120,
    },
    {
        subName: "The Monster",
        breadOption: "Dense Sourdough Bread",
        subSize: "Large",
        drinkChoice: "Coke",
        subTopArray: ["Bacon", "Pulled Pork", "Green Peppers", "Red Onion", "Mayo", "Tomatoes", "Cheese"],
        orderTotal: 105,
    },
    {
        subName: "Greg's Fav",
        breadOption: "Ciabatta Bread",
        subSize: "Medium",
        drinkChoice: "Pine Nut",
        subTopArray: ["Lettuce", "Red Onion", "Tomatoes", "Cheese", "Salami"],
        orderTotal: 85,
    },
    {
        subName: "Hammy Sammy",
        breadOption: "Sub Rolls",
        subSize: "Large",
        drinkChoice: "Fanta Orange",
        subTopArray: ["Bacon", "Sandwich Ham", "Lettuce", "Tomatoes",],
        orderTotal: 105,
    },
    {
        subName: "Sub Sub Salami",
        breadOption: "Hoagie Rolls",
        subSize: "Small",
        drinkChoice: "Coke",
        subTopArray: ["Salami", "Lettuce", "Tomatoes", "Cheese"],
        orderTotal: 90,
    },
    {
        subName: "Turkey Deluxe",
        breadOption: "Dense Sourdough Bread",
        subSize: "Large",
        drinkChoice: "7 Up",
        subTopArray: ["Smoked Turkey Ham", "Lettuce", "Cucumber", "Yellow Onion", "Mozzarella Cheese"],
        orderTotal: 120,
    },
    {
        subName: "Pure Luxury",
        breadOption: "Sub Rolls",
        subSize: "Large",
        drinkChoice: "None",
        subTopArray: ["Pastrami", "Red Onion", "Red Onion", "Tomatoes", "Lettuce", "Mozzarella Cheese"],
        orderTotal: 130,
    },
    {
        subName: "Grinder",
        breadOption: "Hoagie Rolls",
        subSize: "Small",
        drinkChoice: "None",
        subTopArray: ["Sandwich Ham", "Lettuce", "Tomatoes", "Cheese", "Secret Sauce"],
        orderTotal: 115,
    },
]